version: '2'
services:
  web:
    build: .
    links:
      - db:db
      - redis:redis
      - kafka:kafka
    depends_on:
      - db
      - redis
      - kafka
    environment:
      KAFKA_SERVER: kafka:9092
  redis:
    image: redis
  db:
    image: postgres
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ZK_CONNECT: zookeeper:2181
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST_NAME: localhost
      TOPICS: users,common
