create domain dm_pk as integer;
create domain dm_order as integer;
create domain dm_ref as integer;
create domain dm_ref_nn as integer;
create domain dm_bool as boolean;
create domain dm_bool_true as boolean default true;
create domain dm_bool_false as boolean default false;
create domain dm_date as date;
create domain dm_date_nn as date;
create domain dm_date_now as date default now();
create domain dm_date_now_nn as date default now();
create domain dm_time as time;
create domain dm_time_nn as time;
create domain dm_time_now as time default now();
create domain dm_time_now_nn as time default now();
create domain dm_datetime as timestamp;
create domain dm_datetime_nn as timestamp;
create domain dm_datetime_now as timestamp default now();
create domain dm_datetime_now_nn as timestamp default now();
create domain dm_text_micro as varchar(16);
create domain dm_text_micro_nn as varchar(16);
create domain dm_text_mini as varchar(32);
create domain dm_text_mini_nn as varchar(32);
create domain dm_text_small as varchar(64);
create domain dm_text_small_nn as varchar(64);
create domain dm_text_medium as varchar(256);
create domain dm_text_medium_nn as varchar(256);
create domain dm_text_large as varchar(1024);
create domain dm_text_large_nn as varchar(1024);
create domain dm_text_xlarge as varchar(3072);
create domain dm_text_xlarge_nn as varchar(3072);
create domain dm_text_xxlarge as varchar(6144);
create domain dm_text_xxlarge_nn as varchar(6144);
create domain dm_text as text;
create domain dm_text_nn as text;
create domain dm_text_lang as json;
create domain dm_text_lang_nn as json;
create domain dm_synonym as varchar(256);
create domain dm_synonym_nn as varchar(256);
create domain dm_password as varchar(32);
create domain dm_password_nn as varchar(32);
create domain dm_color as varchar(7);
create domain dm_color_nn as varchar(7);
create domain dm_email as varchar(64);
create domain dm_email_nn as varchar(64);
create domain dm_int as integer;
create domain dm_int_nn as integer default 0;
create domain dm_float as numeric(12,4);
create domain dm_float_nn as numeric(12,4) default 0;
create domain dm_cost as numeric(12,2);
create domain dm_cost_nn as numeric(12,2) default 0;
create domain dm_json as json;
create domain dm_json_nn as json;
create domain dm_jsonb as jsonb;
create domain dm_jsonb_nn as jsonb;
create domain dm_int_range as int4range;
create domain dm_int_range_nn as int4range;
create domain dm_float_range as numrange;
create domain dm_float_range_nn as numrange;
create domain dm_date_range as daterange;
create domain dm_date_range_nn as daterange;
create domain dm_datetime_range as tsrange;
create domain dm_datetime_range_nn as tsrange;
create domain dm_interval_year as interval year;
create domain dm_interval_year_nn as interval year;
create domain dm_interval_month as interval month;
create domain dm_interval_month_nn as interval month;
create domain dm_interval_day as interval day;
create domain dm_interval_day_nn as interval day;
create domain dm_interval_hour as interval hour;
create domain dm_interval_hour_nn as interval hour;
create domain dm_interval_minute as interval minute;
create domain dm_interval_minute_nn as interval minute;
create domain dm_interval_second as interval second;
create domain dm_interval_second_nn as interval second;
create domain dm_tel as varchar(32);
create domain dm_tel_nn as varchar(32);
create domain dm_url as varchar(256);
create domain dm_url_nn as varchar(256);
create domain dm_microenum as varchar(16);
create domain dm_microenum_nn as varchar(16);
create domain dm_smallenum as varchar(64);
create domain dm_smallenum_nn as varchar(64);
create domain dm_enum as varchar(256);
create domain dm_enum_nn as varchar(256);
create domain dm_file as varchar(256);
create domain dm_file_nn as varchar(256);
create domain dm_image as json;
create domain dm_image_nn as json;
create domain dm_gps as varchar(64);
create domain dm_gps_nn as varchar(64);
create domain dm_typeahead as varchar(256);
create domain dm_typeahead_nn as varchar(256);
create domain dm_typeahead_list as varchar(1024);
create domain dm_typeahead_list_nn as varchar(1024);
create domain dm_languages as jsonb;
